auto: true
pygments: true

title : Cayenne by Example
tagline: Cayenne by Example illustrates some of the major features of the Apache Cayenne framework through standalone examples.
author :
  name : Michael Gentry
  github : mrg

