auto: true
pygments: true
markdown: rdiscount

title : Cayenne by Example
tagline: Illustrating some of the major features of the Apache Cayenne ORM framework using simple examples.
author :
  name : Michael Gentry
  github : mrg

